-- V2__update_ids_to_bigint.sql

-- Change primary key columns from SERIAL/INTEGER to BIGSERIAL/BIGINT
ALTER TABLE T_USER ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE T_CAPSULE ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE T_CONTENT ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE T_NOTIFICATION ALTER COLUMN id SET DATA TYPE BIGINT;

-- Change foreign key columns to match the new BIGINT data type
ALTER TABLE T_CAPSULE ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE T_CONTENT ALTER COLUMN capsule_id SET DATA TYPE BIGINT;
ALTER TABLE T_NOTIFICATION ALTER COLUMN capsule_id SET DATA TYPE BIGINT;
ALTER TABLE capsule_user ALTER COLUMN capsule_id SET DATA TYPE BIGINT;
ALTER TABLE capsule_user ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE notification_user ALTER COLUMN notification_id SET DATA TYPE BIGINT;
ALTER TABLE notification_user ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE user_followers ALTER COLUMN user_id SET DATA TYPE BIGINT;
ALTER TABLE user_followers ALTER COLUMN follower_id SET DATA TYPE BIGINT;
