image: node:latest

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - ./npm

before_script:
  - npm ci --cache .npm --prefer-offline

stages:
  - build
  - test
  - lint
  - deploy

build-stage:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build
    expire_in: 1 day

test-stage:
  stage: test
  script:
    - npm run test

eslint-stage:
  stage: lint
  script:
    - npm i -g eslint@8
    - npm install eslint-plugin-react-hooks
    - npm i @react-hooks-library/core
    - npm install react-hooks
    - eslint ./src/** ./src/pages/** ./src/pages/meal/** ./src/pages/categories/** ./src/components/footer/** ./src/components/form/** ./src/components/NavBar/**
  allow_failure: true

pages:
  stage: deploy
  when: manual
  dependencies:
    - build-stage
  script:
    - rm -rf public
    - cp build/index.html build/404.html
    - ls -R
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
