version: "3.9"
name: time-capsule

services:
  postgres:
    extends:
      service: postgres
      file: docker-compose-postgresql.yaml
  time-capsule-service:
    container_name: service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      CORS_ALLOWED_ORIGIN: "*"
#      SPRING_DATASOURCE_URL: "jdbc:postgresql://time-capsule-service-host:5432/time-capsule"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ep-plain-snow-a2y3jxg7.eu-central-1.aws.neon.tech/timecapsule?user=timecapsule_owner&password=tLKWQu1FgIP0&sslmode=require"



    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5

