# docker-compose.yml
version: "3.9"
name: time-capsule

services:
  postgres:
    extends:
      file: docker-compose-postgresql.yaml
      service: postgres

  time-capsule-service:
    container_name: time-capsule-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      CORS_ALLOWED_ORIGIN: "http://localhost:3000"
      #SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/timecapsule"
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      - postgres
    networks:
      - time-capsule-network

networks:
  time-capsule-network:
    driver: bridge