##### -- DATABASE -- #####
# spring.datasource.url=jdbc:postgresql://localhost:45000/time-capsule
# spring.datasource.username=admin
# spring.datasource.password=admin
##### -- BASIC AUTH -- #####
# admin.username=admin
# admin.password=password
##### -- CORS -- #####
# *cors.allowed-origins=http://localhost:3000