##### -- DATABASE -- #####
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-plain-snow-a2y3jxg7.eu-central-1.aws.neon.tech/timecapsule?user=timecapsule_owner&password=tLKWQu1FgIP0&sslmode=require
spring.datasource.hikari.maximum-pool-size=10
admin.username=myAdmin
admin.password=mySecretPassword
spring.jpa.generate-ddl = true
spring.jpa.hibernate.ddl-auto = update
jwt.secret=R1b$Y8j9!Fq3WzD2T7mP4X5af8V598ga
baseUrl=https://time-capsule-phi.vercel.app/


server.ssl.key-store=classpath:springboot.p12
server.ssl.key-store-password=password
server.ssl.key-store-type=pkcs12
server.ssl.key-alias=springboot
server.ssl.key-password=password

#spring.datasource.username=postgres
#spring.datasource.password=HesloKleslo
! Prevents problems for enum mapping
spring.datasource.hikari.data-source-properties.stringtype=unspecified
##### -- FLYWAY -- #####
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db
spring.flyway.create-schemas=true
spring.flyway.mixed=true
##### -- API-DOCS -- #####
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
##### -- SWAGGER -- #####
springdoc.swagger-ui.operationsSorter=method
##### -- EXCEPTIONS -- #####
server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=false

##### -- CORS -- #####
cors.allowed-origins=*

#spring.profiles.active=local
#server.servlet.context-path=/api



##### -- SPRING MAIL -- #####

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=timecapsulepm2@gmail.com
spring.mail.password=dlgx qgyl aqvk xldk

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# OAuth2 Google SSO configuration
spring.security.oauth2.client.registration.google.client-id=863967100823-mg02425139j9e6ha3s8ptjn2jplr0nsp.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=openid, profile, email
spring.security.oauth2.client.registration.google.client-name=Google

# Provider settings (default settings work for Google, but you can add them explicitly)
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://openidconnect.googleapis.com/v1/userinfo
spring.security.oauth2.client.provider.google.jwk-set-uri=https://www.googleapis.com/oauth2/v3/certs
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.oauth2.client=DEBUG
logging.level.org.springframework.oauth2=DEBUG

#Connection to FE
server.port=8080
cors.allowed.origins=http://localhost:3000, https://time-capsule-phi.vercel.app
spring.application.name=time-capsule-service
spring.main.allow-circular-references=true

