##### -- DATABASE -- #####
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
! Prevents problems for enum mapping
spring.datasource.hikari.data-source-properties.stringtype=unspecified
##### -- FLYWAY -- #####
spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db
spring.flyway.create-schemas=true
spring.flyway.mixed=true
##### -- API-DOCS -- #####
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
##### -- SWAGGER -- #####
springdoc.swagger-ui.operationsSorter=method
##### -- EXCEPTIONS -- #####
server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=false

spring.profiles.active=local
server.servlet.context-path=/api