##### -- DATABASE -- #####
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://ep-plain-snow-a2y3jxg7.eu-central-1.aws.neon.tech/timecapsule?user=timecapsule_owner&password=tLKWQu1FgIP0&sslmode=require
spring.datasource.hikari.maximum-pool-size=10
admin.username=myAdmin
admin.password=mySecretPassword
spring.jpa.generate-ddl = true

#spring.datasource.username=postgres
#spring.datasource.password=HesloKleslo
! Prevents problems for enum mapping
spring.datasource.hikari.data-source-properties.stringtype=unspecified
##### -- FLYWAY -- #####
#spring.flyway.enabled=true
#spring.flyway.schemas=public
#spring.flyway.locations=classpath:db
#spring.flyway.create-schemas=true
#spring.flyway.mixed=true
##### -- API-DOCS -- #####
springdoc.api-docs.path=/api-docs
springdoc.api-docs.enabled=true
##### -- SWAGGER -- #####
springdoc.swagger-ui.operationsSorter=method
##### -- EXCEPTIONS -- #####
server.error.include-message=always
spring.mvc.throw-exception-if-no-handler-found=false

##### -- CORS -- #####
cors.allowed-origins=*

#spring.profiles.active=local
#server.servlet.context-path=/api
