##### -- DATABASE -- #####
 spring.datasource.url=jdbc:postgresql://localhost:45000/time-capsule
 spring.datasource.username=admin
 spring.datasource.password=admin
##### -- BASIC AUTH -- #####
 admin.username=admin
 admin.password=password
##### -- CORS -- #####
cors.allowed-origins=http://localhost:3000

baseUrl=http://localhost:8080

jwt.secret=R1b$Y8j9!Fq3WzD2T7mP4X5af8V598ga
spring.main.allow-circular-references=true